routes:
  /links/:
    controller: channel
    filter: tag:link
  /micros/:
    controller: channel
    filter: tag:micro
  /de/:
    controller: channel
    filter: tag:de
  /en/:
    controller: channel
    filter: tag:en
  /posts/:
    controller: channel
    filter: tag:-[link,micro]
  /pictures/:
    controller: channel
    template:
      - pictures
    filter: tag:picture

collections:
  /:
    permalink: /{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
